server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#h2:console enable login h2 console from browser to show db
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#ddl auto update means create tables as per req when server start so no need to manually create table
    hibernate:
      ddl-auto: update
#show sql truue prin all qery on console
    show-sql: true